# Generated by Django 4.2.1 on 2023-05-25 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0004_alter_categoriesofproducts_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsofproducts',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapi.categoriesofproducts'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapi.groupsofproducts'),
        ),
    ]
